(function($){'use strict';
const state={products:[],filtered:[],pallet:{},activeCategory:'all',searchTerm:'',FREE_SHIP_THRESHOLD:1500,COMPETITOR_UNIT_PRICE:67};
function init(){fetchProducts();bindEvents();}
function fetchProducts(){$('#opb-loading').show();$('#opb-product-grid').hide();$.ajax({url:ofo_pallet_data.ajax_url,method:'POST',data:{action:'ofo_get_pallet_products',nonce:ofo_pallet_data.nonce},success:function(res){$('#opb-loading').hide();if(res.success&&res.data&&res.data.length){state.products=res.data;applyFilters();renderGrid();}else{$('#opb-empty').show();}},error:function(){$('#opb-loading').hide();$('#opb-empty').text('Failed to load products. Please refresh.').show();}});}
function applyFilters(){let list=state.products;if(state.activeCategory!=='all'){list=list.filter(p=>p.categories&&p.categories.includes(state.activeCategory));}if(state.searchTerm.trim()){const term=state.searchTerm.toLowerCase();list=list.filter(p=>p.name.toLowerCase().includes(term));}state.filtered=list;}
function renderGrid(){const $grid=$('#opb-product-grid');$grid.empty();if(!state.filtered.length){$('#opb-empty').show();$grid.hide();return;}$('#opb-empty').hide();$grid.show();state.filtered.forEach(product=>{const qty=state.pallet[product.id]||0;const caseSize=parseInt(product.case_pack)||1;const price=parseFloat(product.price)||0;const retailPrice=caseSize>1?(caseSize*state.COMPETITOR_UNIT_PRICE):parseFloat(product.retail_price)||(price*2);const perUnit=caseSize>1?(price/caseSize).toFixed(2):null;const shots=parseInt(product.shot_count)||0;const imgHtml=product.image?`<img class="opb-product-img" src="${esc(product.image)}" alt="${esc(product.name)}" loading="lazy">`:`<div class="opb-product-img-placeholder">🎆</div>`;const shotTag=shots>0?`<span class="opb-meta-tag opb-meta-tag--shots">💥 ${shots} shots</span>`:'';const piecesTag=caseSize>1?`<span class="opb-meta-tag opb-meta-tag--pieces">📦 ${caseSize}/case</span>`:'';const perUnitHtml=perUnit?`<span class="opb-product-per-unit">≈ $${perUnit} per unit</span>`:'';$grid.append(`<div class="opb-product-card${qty>0?' in-pallet':''}" data-id="${product.id}"><div class="opb-product-img-wrap">${imgHtml}${product.category_label?`<span class="opb-product-category-badge">${esc(product.category_label)}</span>`:''}</div><div class="opb-product-body"><p class="opb-product-name">${esc(product.name)}</p><div class="opb-product-meta">${shotTag}${piecesTag}</div><div class="opb-product-pricing"><span class="opb-product-price">$${price.toFixed(2)}</span><span class="opb-product-retail">$${retailPrice.toFixed(2)}</span>${perUnitHtml}</div><div class="opb-qty-controls"><button class="opb-qty-btn opb-qty-minus" data-id="${product.id}">−</button><input class="opb-qty-input" type="number" min="0" value="${qty}" data-id="${product.id}" readonly><button class="opb-qty-btn opb-qty-plus" data-id="${product.id}">+</button></div></div></div>`);});}
function setQty(id,qty){qty=Math.max(0,parseInt(qty)||0);if(qty===0){delete state.pallet[id];}else{state.pallet[id]=qty;}$(`.opb-qty-input[data-id="${id}"]`).val(qty);$(`.opb-product-card[data-id="${id}"]`).toggleClass('in-pallet',qty>0);updateSidebar();}
function updateSidebar(){const ids=Object.keys(state.pallet);let ti=0,tp=0,ts=0,yt=0;ids.forEach(id=>{const p=state.products.find(x=>x.id==id);if(!p)return;const q=state.pallet[id],pr=parseFloat(p.price)||0,cs=parseInt(p.case_pack)||1,sh=parseInt(p.shot_count)||0;ti+=q;tp+=q*cs;ts+=q*sh;yt+=q*pr;});const rt=tp*state.COMPETITOR_UNIT_PRICE;const sv=rt-yt,pct=rt>0?Math.round((sv/rt)*100):0;$('#opb-stat-items').text(ti);$('#opb-stat-pieces').text(tp.toLocaleString());$('#opb-stat-shots').text(ts.toLocaleString());$('#opb-your-price').text('$'+yt.toFixed(2));$('#opb-retail-price').text('$'+rt.toFixed(2));$('#opb-savings-amount').text('$'+sv.toFixed(2));$('#opb-savings-pct').text(pct>0?pct+'% off':'');const bar=Math.min(100,(yt/state.FREE_SHIP_THRESHOLD)*100);$('#opb-progress-fill').css('width',bar+'%').toggleClass('complete',bar>=100);if(bar>=100){$('#opb-ship-status').text('🎉 FREE Shipping Unlocked!');$('#opb-ship-amount').text('');}else{$('#opb-ship-status').text(`Add $${(state.FREE_SHIP_THRESHOLD-yt).toFixed(2)} for FREE shipping`);$('#opb-ship-amount').text(`$${yt.toFixed(2)} / $${state.FREE_SHIP_THRESHOLD}`);}renderSelectedItems(ids);$('#opb-add-to-cart-btn').prop('disabled',ids.length===0);}
function renderSelectedItems(ids){const $l=$('#opb-selected-items');$l.empty();if(!ids.length){$l.append('<p class="opb-empty-cart">No items added yet.<br>Pick products from the left →</p>');return;}ids.forEach(id=>{const p=state.products.find(x=>x.id==id);if(!p)return;const q=state.pallet[id],lt=(q*(parseFloat(p.price)||0)).toFixed(2);$l.append(`<div class="opb-selected-item" data-id="${id}"><div class="opb-selected-item-name">${esc(p.name)}</div><span class="opb-selected-item-qty">×${q}</span><span class="opb-selected-item-price">$${lt}</span><button class="opb-selected-item-remove" data-id="${id}" title="Remove">×</button></div>`);});}
function addPalletToCart(){const $b=$('#opb-add-to-cart-btn');const ids=Object.keys(state.pallet);if(!ids.length)return;$b.prop('disabled',true).html('<span>⏳</span> Adding to Cart...');const items=ids.map(id=>({product_id:id,quantity:state.pallet[id]}));$.ajax({url:ofo_pallet_data.ajax_url,method:'POST',data:{action:'ofo_add_pallet_to_cart',nonce:ofo_pallet_data.nonce,items:JSON.stringify(items)},success:function(res){if(res.success){showToast('🎉 Pallet added! Redirecting...');setTimeout(()=>{window.location.href=ofo_pallet_data.cart_url;},1500);}else{showToast('❌ '+(res.data||'Error'),true);$b.prop('disabled',false).html('<span>🛒</span> Add Pallet to Cart');}},error:function(){showToast('❌ Something went wrong.',true);$b.prop('disabled',false).html('<span>🛒</span> Add Pallet to Cart');}});}
function showToast(msg,isErr){const $t=$('#opb-toast');$t.text(msg).css('background',isErr?'#dc3545':'').addClass('show');setTimeout(()=>$t.removeClass('show'),3000);}
function bindEvents(){$(document).on('click','.opb-filter-btn',function(){$('.opb-filter-btn').removeClass('active');$(this).addClass('active');state.activeCategory=$(this).data('category');applyFilters();renderGrid();});$('#opb-search').on('input',debounce(function(){state.searchTerm=$(this).val();applyFilters();renderGrid();},300));$(document).on('click','.opb-qty-plus',function(){const id=$(this).data('id');setQty(id,(state.pallet[id]||0)+1);});$(document).on('click','.opb-qty-minus',function(){const id=$(this).data('id');setQty(id,(state.pallet[id]||0)-1);});$(document).on('click','.opb-selected-item-remove',function(){setQty($(this).data('id'),0);});$('#opb-add-to-cart-btn').on('click',addPalletToCart);$('#opb-clear-btn').on('click',function(){state.pallet={};applyFilters();renderGrid();updateSidebar();});}
function esc(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function debounce(fn,d){let t;return function(...a){clearTimeout(t);t=setTimeout(()=>fn.apply(this,a),d);};}
$(document).ready(init);
})(jQuery);
